name: photo_view_example
description: Example of how to use Photo View

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.5.9-pre.94 <2.0.0"

dependencies:
#  flutter_svg:
  photo_view:
    path: ../
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/peanut.gif
    - assets/large-image.jpg
    - assets/small-image.jpg
    - assets/gallery1.jpg
    - assets/gallery2.jpg
    - assets/gallery3.jpg
    - assets/firefox.svg

  fonts: 
    - family: PTSans 
      fonts:
        - asset: assets/fonts/ptasans-regular.ttf
        - asset: assets/fonts/ptasans-bold.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
